// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using THEAI_BE.Data;

#nullable disable

namespace THEAI_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250610033237_SeedInitialUsers")]
    partial class SeedInitialUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("THEAI_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 10, 3, 32, 37, 326, DateTimeKind.Utc).AddTicks(8634),
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 10, 3, 32, 37, 326, DateTimeKind.Utc).AddTicks(8770),
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 10, 3, 32, 37, 326, DateTimeKind.Utc).AddTicks(8772),
                            Email = "charlie@example.com",
                            FirstName = "Charlie",
                            LastName = "Clark"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
